[package]
name = "dse-dsp-sys"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
adpcm-xq-sys = { version = "0.1.5", features = ["nds"] }

[build-dependencies]
cc = "1.0"
