[package]
name = "dse-dsp-sys"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adpcm-xq-sys = { version = "0.1.1", features = ["nds"] }

[build-dependencies]
cc = "1.0"
